name: ControlArticles

#run on Markdown files edited
on:
  push:
    paths:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Execute python
        run: |
          python3 -m pip install --upgrade pip
          python3 .github/workflows/ArticlesController.py

      - name: Commit changes
        run: |
          git config --global user.name "action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Update Articles.json"
          git push
