name: ControlArticles

#run on Markdown files edited
on:
  push:
    paths:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Execure python
        run: |
          python3 -m pip install --upgrade pip
          python3 .github/workflows/ArticlesController.py
